### PR TITLE
WIP: OSD-6853: Generate `REPO_DIGEST` parameter

### PR DESCRIPTION
**Pull request by 2uasimojo**
With this commit, if your service requests it by setting `USE_REPO_DIGEST = "true"` *and* both `REGISTRY_IMG` and `IMAGE_TAG` are known, saasherder will add a `REPO_DIGEST` parameter before processing your template. The `REPO_DIGEST` parameter will have the form `{REGISTRY_IMG}@sha256:{hash}`. For example, given:
- `USE_REPO_DIGEST = "true"`
- `REGISTRY_IMG = "quay.io/app-sre/osd-metrics-exporter-registry"`
- `IMAGE_TAG` = "production-2cb14b0"`
...we will set:
- `REPO_DIGEST = "quay.io/app-sre/osd-metrics-exporter-registry@sha256:c94893c302cf5ef8aae0581f60bf59c3f65860aeefdd6046440bdc95f258c26e"`

OSD-6853

### CODE REVIEW

**Comment by 2uasimojo** [comment]
/hold

TODO:
- Buy-in.
- Probably need to get `docker` into package requirements.
- Test - how??

**Comment by jharrington22** [comment]
This from my perspective looks ok since its opt-in via parameter in the saas config file and shouldn't effect other use cases for saasherder.

It would be nice if we didn't have to rely on the remote repository for the image digest and pass it from the build since it could change. This behavior however is no different to what we have today as the container image for said tag could change.

**Comment by jharrington22** [comment]
@2uasimojo small nit. Replace REPO_DIGEST with IMAGE_DIGEST since its specific to the image and not the repo.

**Comment by 2uasimojo** [comment]
> @2uasimojo small nit. Replace REPO_DIGEST with IMAGE_DIGEST since its specific to the image and not the repo.

I'm using `REPO_DIGEST` to correspond with what docker itself calls it -- `RepoDigests`. (I assume that name derives from "repo (URI) + (image) digest".)

**Comment by 2uasimojo** [comment]
I'm told this code isn't used anymore, at least for the things we (OSD) care about. Will propose similar change in qontract-reconcile.

**Comment by 2uasimojo** [comment]
https://github.com/app-sre/qontract-reconcile/pull/1473

**Pull request closed without merging**
