### PR TITLE
add support for CatalogSource templates image location

### PR DESCRIPTION
**Pull request by xyntrix**
@jmelis ptal

### CODE REVIEW

**Review by jmelis — CHANGES_REQUESTED** [review]
It seems to me there's a syntax error there? there's an except without its corresponding try. Does this work for you?

Also I think it would be nicer to retrieve the image path based on the kind. Having nested try/except blocks is hard to.understand.

**Comment by xyntrix** [comment]
> It seems to me there's a syntax error there? there's an except without its corresponding try. Does this work for you?
> 
> Also I think it would be nicer to retrieve the image path based on the kind. Having nested try/except blocks is hard to.understand.

whoops! forgot to commit that crucial try:..  initially i thought the same re: explicit check by type, but realized if we start adding a pattern of looking for specific kind:'s.. that itself can itself be tedious to maintain for every custom object type coming out, where if there's a generic short distinct set of locations where we can find the image value, that may be easier to parse and likely requires less future updates (assuming new types follow the same patterns).

**Review by jmelis — CHANGES_REQUESTED** [review]
there's still a syntax error, the try/except are not aligned. Please test before submitting PR

**Comment by xyntrix** [comment]
> 
> 
> there's still a syntax error, the try/except are not aligned. Please test before submitting PR

i see that.  i figured out what is up: "make test" has been passing because it's not actually checking check_images.py with even a basic lint check. i can add that to the tests, at least for a very simple sanity  check.. i'll include with this mr.

**Comment by xyntrix** [comment]
adding tests, and using app-sre/quay/ as a generic (hopefully static?) test target. quick sanity check, manually:

```
$ python2 check_image.py tests/data/fixtures/cs-image-fail.yaml
['ERROR', 'quay.io/app-sre/quay:nope-b4df00d', 'time="2020-04-23T16:42:43-07:00" level=fatal msg="Error reading manifest nope-b4df00d in quay.io/app-sre/quay: manifest unknown: manifest unknown" \n']
...
$ python2 check_image.py tests/data/fixtures/cs-image-pass.yaml
['OK', 'quay.io/app-sre/quay:latest']
```

**Comment by jmelis** [comment]
much better, thanks @mmclanerh 

> but realized if we start adding a pattern of looking for specific kind:'s.. that itself can itself be tedious to maintain for every custom object type coming out

Well, let's say we use your current PR and keep adding support for other resources that have the image in a different place. In your model we would add it as another nested try/except inside the last except... we could end up with something like:

```python
for i in anymarkup.parse_file(OPENSHIFT_TEMPLATE, force_types=None)["items"]:
    try:
        for c in i["spec"]["template"]["spec"]["containers"]:
            images.add(c["image"])
    except KeyError:
        try:
            images.add(i["spec"]["path1"]["image"])
        except KeyError:
            try:
                images.add(i["spec"]["path2"]["image"])
            except KeyError:
                try:
                    images.add(i["spec"]["path3"]["image"])
                except KeyError:
                    pass
```
And if we keep adding... :)

So, I suggest this, same effect, easier to read and to maintain:
```python
for i in anymarkup.parse_file(OPENSHIFT_TEMPLATE, force_types=None)["items"]:
    try:
        for c in i["spec"]["template"]["spec"]["containers"]:
            images.add(c["image"])
    except KeyError:
        pass

    try:
        images.add(i["spec"]["image"])
    except KeyError:
        pass
```

**Comment by xyntrix** [comment]
totally fair assessment and +1 to that.
..super hacky quick sanity check (until i add the formal test..)
```
$ python2 check_image.py tests/data/fixtures/customresource/cs-image-pass.yaml
['OK', 'quay.io/app-sre/quay:latest']

$ python2 check_image.py tests/data/fixtures/customresource/cs-image-fail.yaml
['ERROR', 'quay.io/app-sre/quay:nope-b4df00d', 'time="2020-04-23T17:07:01-07:00" level=fatal msg="Error reading manifest nope-b4df00d in quay.io/app-sre/quay: manifest unknown: manifest unknown" \n']
```
 (and thanks for the late night feedback.. dont forget to sleep!)

**Review by jmelis — APPROVED** [review]
LGTM!

**Comment by xyntrix** [comment]
@jmelis  added some very basic positive/negative test cases for check_image.py, as previously there was nothing doing validation. ptal!

**Comment by jmelis** [comment]
hey! this is awesome!! thanks a lot Mike!!! LGTM!

**Pull request merged**
