### PR TITLE
Improves check_image.py repo name processing using library functions

### PR DESCRIPTION
**Pull request by navidshaikh**
Added library function to process repo name and split it into different parts.
check_image.py now uses added library function to process repo name.

### CODE REVIEW

**Comment by jmelis** [comment]
[test]

**Comment by jmelis** [comment]
hi @navidshaikh: does this change the behaviour in some way, or is it mostly refactoring/cosmetic improvement?

**Comment by navidshaikh** [comment]
hi @jmelis: This is mostly focused on refactoring. Improved and segregated the operation to split container repository into parts in library function, covering multiple cases/forms a repository name could take. This changeset should improve `check_image.py` script to be able to work with different input forms of a container repository.

The utility function added in library can work with possible forms of 
 - registry URL (with and without ports)
 - container image name (with one or multiple namespaces provided)
 - tags (either provided or assumed default `latest`)

```
example:
r.c.o/prod/foo/bar:tag1
r.c.o/foo/bar:tag1
r.c.o/foo:tag1
foo/bar:tag1
bar:tag1
bar
```

**Comment by jmelis** [comment]
@navidshaikh thanks a lot for the contribution. I didn't merge immediately because support for authenticated quay.io had to be added shortly.

Yesterday I was looking into this, and adding support for quay was a quite inconvenient, so  @jfchevrette proposed that we use [skopeo](https://github.com/projectatomic/skopeo) and the code is much simpler now:
https://github.com/openshiftio/saasherder/blob/ba90efe827dd22ca22220e7c27ee8a928b2d553c/check_image.py

I'm going to close this PR as all this logic is already implemented at the skopeo level, and we don't need to reinvent the wheel.

**Pull request closed without merging**
